create database Retail_Case_Study
select * from Customer
select * from prod_cat_info
select * from Transactions

alter table Transactions
 add constraint FK_ORDER_REFERENCE_Transactions foreign key (cust_id)
 references Customer (customer_id)
go

/*
alter table Transactions
 add constraint FK_ORDER_REFERENCE_Trans foreign key (prod_subcat_code)
 references prod_cat_info (prod_sub_cat_code)
go*/

alter table Customer alter COLUMN DOB date
alter table Transactions alter COLUMN total_amt bigint
alter table Transactions alter COLUMN Tax int

use Retail_Case_Study
go
select TABLE_SCHEMA,TABLE_NAME,COLUMN_NAME,DATA_TYPE, CHARACTER_MAXIMUM_LENGTH from INFORMATION_SCHEMA.COLUMNS 
where table_name='Transactions'

--********************************DATA PREPARATION AND UNDERSTANDING*********************************************

--1.	What is the total number of rows in each of the 3 tables in the database?
select count(*) from Customer
select count(*) from Transactions
select count(*) from prod_cat_info

--2.	What is the total number of transactions that have a return?
select count(distinct transaction_id)[count], sum(Qty) [Quantity returned] from Transactions
where Qty < 0 

--3.	As you would have noticed, the dates provided across the datasets are not in a correct format.
--As first steps, pls convert the date variables into valid date formats before proceeding ahead.
alter table Customer alter COLUMN DOB date
alter table Transactions alter Column tran_date date

--4.	What is the time range of the transaction data available for analysis?
--Show the output in number of days, months and years simultaneously in different columns.
-- can use datepart() also

select datediff(day,min( tran_date),max(tran_date))[No of days],
		datediff( month,min(tran_date),max(tran_date))[No of months],
		datediff(year, min(tran_date),max(tran_date))[No of years] from Transactions
 
--5.	Which product category does the sub-category “DIY” belong to?
select prod_cat from prod_cat_info
where prod_subcat='DIY'

--****************************************DATA ANALYSIS**************************************************

--1.	Which channel is most frequently used for transactions? 
select top 1 Store_type, count(*) [Max count] from Transactions
group by Store_type
order by count(*) desc

--2.	What is the count of Male and Female customers in the database?
select Gender, Count(*)[Gender Count] from Customer
group by Gender

--3.	From which city do we have the maximum number of customers and how many?
select top 1 city_code,count(city_code)[Max Count] from Customer
group by city_code
order by [Max Count] desc

--4.	How many sub-categories are there under the Books category?
/*select prod_cat,prod_subcat from prod_cat_info
where prod_cat='Books'*/

select count(prod_subcat) from prod_cat_info
group by prod_cat
having prod_cat='Books'

--5. What is the maximum quantity of products ever ordered?
select p.prod_cat,max(Qty)[MAX Quantity] from Transactions t 
inner join prod_cat_info p on t.prod_cat_code=p.prod_cat_code
group by p.prod_cat
order by [MAX Quantity] desc

--6.	What is the net total revenue generated in categories Electronics and Books?
select prod_cat,sum(t.total_amt)[net total revenue] from Transactions t inner join
prod_cat_info p on t.prod_cat_code=p.prod_cat_code
and t.prod_subcat_code=p.prod_sub_cat_code
where p.prod_cat in ('Electronics','Books')
group by prod_cat

--7.	How many customers have >10 transactions with us, excluding returns?

select distinct cust_id, count(cust_id)[Customer count] from Transactions
where qty > 0
group by cust_id
having count(cust_id) > 10 

--8.	What is the combined revenue earned from the “Electronics” & “Clothing” categories,
--from “Flagship stores”?

select sum(t.total_amt)[Combined revenue] from Transactions t 
inner join prod_cat_info p on
t.prod_subcat_code=p.prod_sub_cat_code and 
t.prod_cat_code = p.prod_cat_code
where t.Store_type='Flagship store' and p.prod_cat in ('Electronics' ,'Clothing')

--9.	What is the total revenue generated from “Male” customers in “Electronics” category?
--Output should display total revenue by prod sub-cat.
select p.prod_subcat,sum(t.total_amt)[Revenue generated by MALE customers] from Customer c
inner join Transactions t on t.cust_id=c.customer_Id
inner join prod_cat_info p on p.prod_sub_cat_code=t.prod_subcat_code and 
t.prod_cat_code = p.prod_cat_code
where c.Gender ='M' and p.prod_cat='Electronics'
group by p.prod_subcat

--10.	What is percentage of sales and returns by product sub category;
--display only top 5 sub categories in terms of sales?
select top 5 p.prod_subcat,count(t.total_amt)*100/(select count(*) from Transactions)[percent of sales] from 
Transactions t 
inner join prod_cat_info p on p.prod_sub_cat_code=t.prod_subcat_code and p.prod_sub_cat_code = t.prod_subcat_code
group by p.prod_subcat
order by [percent of sales] desc

--11.	For all customers aged between 25 to 35 years find what is the net total revenue 
--generated by these consumers in last 30 days of transactions from max transaction date available in the data?

select sum(t.total_amt)[net value]
from Customer c inner join
Transactions t on t.cust_id=c.customer_Id
where datediff(YYYY,dob,getdate())  between 25 and 35 and 
t.tran_date = (select dateadd(dd,-30,max(tran_date)) from Transactions)  

--12. Which product category has seen the max value of returns in the last 3 months of transactions?

select top 1 p.prod_cat,sum(t.total_amt)[Max value] from Transactions t 
inner join prod_cat_info p on p.prod_cat_code=t.prod_cat_code and p.prod_sub_cat_code=t.prod_subcat_code
where tran_date = (select DATEADD(mm,-3,max(tran_date)) from Transactions)
group by p.prod_cat
order by [Max value] desc

--13.Which store-type sells the maximum products; by value of sales amount and by quantity sold?
select top 1 Store_type, sum(total_amt)[Sales Amount]  from Transactions
where Qty = (select max(Qty) from Transactions) 
group by Store_type
order by [Sales Amount] desc

--14.What are the categories for which average revenue is above the overall average.

 Select prod_cat from Transactions t inner join prod_cat_info p
 on t.prod_cat_code=p.prod_cat_code
 group by t.prod_cat_code,prod_cat
 having AVG(total_amt) > (Select AVG(total_amt) from Transactions)

--15.Find the average and total revenue by each subcategory for the categories
--which are among top 5 categories in terms of quantity sold.
select prod_cat, prod_subcat, AVG(total_amt) [Average], SUM(total_amt) [Total_Revenue]
from Transactions t inner join prod_cat_info p ON p.prod_cat_code = t.prod_cat_code 
AND p.prod_sub_cat_code = t.prod_subcat_code
where PROD_CAT IN
 (
		select TOP 5 prod_cat from Transactions tr inner join
		prod_cat_info pc ON pc.prod_cat_code = tr.PROD_CAT_CODE 
		AND pc.prod_sub_cat_code = tr.prod_subcat_code
		GROUP BY PROD_CAT
		ORDER BY SUM(QTY) DESC
 )
 GROUP BY prod_cat, prod_subcat 